<a href="https://colab.research.google.com/github/dlvvkfl88/MSAISCHOOL/blob/main/01_numpy%EB%A7%8C%EB%93%A4%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

### 용어정리

- scalar : 상수값( 10,3.14 , 'korea')
- vector(1차원): [10,20,30], #(3,)
- matrix(2차원): [[10,20,30], [10,20,30]] # (2,3) 2개의벡터 3개의 스칼라
- 3차원:[[[10,20,30], [10,20,30]],[[10,20,30], [10,20,30]]] # 2,2,3
- 4차원 : [[[[10,20,30], [10,20,30]],[[10,20,30], [10,20,30]]]] # 2,2,3

In [ ]:
my = [10,20,30]
print(type(my))


<class 'list'>


## 1 .ndarray 생성방법

In [ ]:
arr1 = np.array([10,20,30])
print(type(arr1))
print(arr1)
arr1

<class 'numpy.ndarray'>
[10 20 30]


array([10, 20, 30])

In [ ]:
arr2 = np.array([[10,20,30],[100,200,300]])
print(arr2)
arr2

[[ 10  20  30]
 [100 200 300]]


array([[ 10,  20,  30],
       [100, 200, 300]])

In [ ]:
arr3 = np.array([10,20,30], dtype=np.float32)
arr3

array([10., 20., 30.], dtype=float32)

In [ ]:
arr4 = np.array([10,20,30],dtype=np.int32)
arr4

array([10, 20, 30])

In [ ]:
arr5 = np.array([10,20,30],dtype=np.int64)
arr5

array([10, 20, 30], dtype=int64)

## ndarray 핵심속성

In [ ]:
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

In [ ]:
arr.dtype

dtype('int32')

In [ ]:
arr.size

5

In [ ]:
arr.shape

(5,)

In [ ]:
arr.ndim

1

In [ ]:
arr1 = np.array([[11,22],[33,44],[55,66]])
arr1

array([[11, 22],
       [33, 44],
       [55, 66]])

In [ ]:
arr1.shape

(3, 2)

In [ ]:
arr1.T

array([[11, 33, 55],
       [22, 44, 66]])

## reshape 함수

In [ ]:
arr2 = np.array([1,2,3,4,5,6])
arr2

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr2.reshape(2,3) # 2,3열로 바꾸라

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2.reshape(2,-1) # 행이 2개이려면 컬럼이 3개일수밖에없다

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2.reshape(-1,3) # 컬럼이 3개려면 행은 2개일수밖에없다
arr2

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr2.reshape(1,3,2) #

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [ ]:
import numpy as np

In [ ]:
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

## 인덱싱: [ 인덱스번호]
- 0,1,2,
- -3,-2,-1

In [ ]:
arr[0]

11

In [ ]:
arr[-1]

55

## 복수개 인덱싱:
[['번호', ' 번호'....]]

In [ ]:
arr[[0,1,3]] # arr = np.array([11,22,33,44,55]) 여기서 11, 22 44 가져옴 0 1 3

array([11, 22, 44])

In [ ]:
arr

array([11, 22, 33, 44, 55])

# boolean indexing
 - [[True, False]]

In [ ]:
arr[[True,False,False,True,True]]

array([11, 44, 55])

In [ ]:
arr

array([11, 22, 33, 44, 55])

## Slicing(슬라이싱)

-[시작:끝:증가치]
- 시작 <- index < 끝

In [ ]:
arr[1:4:1] # 1<=index<4 1씩증가 1,2,3

array([22, 33, 44])

In [ ]:
arr[0:4] # 0 < index < 40,1,2,3

array([11, 22, 33, 44])

In [ ]:
arr[1:]

array([22, 33, 44, 55])

In [ ]:
arr[:-1]

array([11, 22, 33, 44])

## 연산(산술관계논리)
- borad casting 연산대상 자동학괒ㅇ
- elemnet wise : 동일한 인덱스끼리 연ㄱ산

In [ ]:
arr + 1 # [11,22,33,44,55] + [1,1,1,1,]

array([12, 23, 34, 45, 56])

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr+arr1

array([12, 24, 36, 48, 60])

 ###  퀴즈
 #연봉데이터가 있을때 각연봉에 대한 # 세금 3.3%을 제한 실수령액을 구하시오

In [ ]:
salary = np.array([1000,2000,3000,4000,5000])
salary-salary*0.333
salary*0.967

array([ 967., 1934., 2901., 3868., 4835.])

## 관계연산자

In [ ]:
arr>30

array([False, False,  True,  True,  True])

In [ ]:
arr[arr>30] # 트루인 인덱스만 나와라 # boolean indexing True False로 나옴

array([33, 44, 55])

In [ ]:
## 논리연산자 : * , |,~ and & or | not ~

In [ ]:
arr[(arr==11)|(arr==55)]

array([11, 55])

In [ ]:
(arr >20) & (arr<50)

array([False,  True,  True,  True, False])

In [ ]:
arr[(arr >20) & (arr<50)]

array([22, 33, 44])

In [ ]:
arr

array([11, 22, 33, 44, 55])

In [ ]:
~((arr >20) & (arr<50))

array([ True, False, False, False,  True])

In [ ]:
arr[~((arr >20) & (arr<50))]

array([11, 55])

## 추가

In [ ]:
np.append(arr, [100,200]) # 맨끝에 추가

array([ 11,  22,  33,  44,  55, 100, 200])

In [ ]:
np.insert(arr, 1, [1,2]) # arr에 1번쨰 인덱스 [1,2]를 추가해라

array([11,  1,  2, 22, 33, 44, 55])

In [ ]:
arr

array([11, 22, 33, 44, 55])

## 수정


In [ ]:
arr[0] =111

In [ ]:
arr[1:3] = [222,333]

In [ ]:
# 삭제
np.delete(arr, [0,2])

array([222,  44,  55])

In [ ]:
arr

array([111, 222, 333,  44,  55])

In [ ]:
np.where()

In [ ]:
arr

array([111, 222, 333,  44,  55])

In [ ]:
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

In [ ]:
np.where(arr>30, "합격","불합격") # 해당조건에 인덱스번호 알려줌

array(['불합격', '불합격', '합격', '합격', '합격'], dtype='<U3')

In [ ]:
np.select([arr>40,arr>20,arr>0], ['A','B','C']) # 40이상이면 a 20 이상 b 이런식으로 매칭 np.select()

array(['C', 'B', 'B', 'A', 'A'], dtype='<U3')

# 정렬 넘파이

In [ ]:
np.sort(arr)

array([11, 22, 33, 44, 55])

In [ ]:
arr

array([11, 22, 33, 44, 55])

In [ ]:
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

## 통계

In [ ]:
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

In [ ]:
arr.sum()

165

In [ ]:
arr.mean()

33.0

In [ ]:
np.mean(arr)

33.0

In [ ]:
arr.max() # np.max(arr)

55

In [ ]:
arr.std()

15.556349186104045

In [ ]:
np.median(arr)

33.0

In [ ]:
np.quantile(arr,[0.25,0.5,0.75])

array([22., 33., 44.])

In [ ]:
arr

array([11, 22, 33, 44, 55])

### 연습문제
kor = np.array([60,55,70,30,20,90])

1.국어점수가 가장큰값 구하시오
2. 국어점수 80점 이상 값 구하시오
3. 국어점수 50이상 80이하 구하시오
4. 국어점수 의 평균을 구하시오
5. 국어점수총합을 구하시오
6. 국어점수 40점이하 데이터를 삭제하시요
7.국어점수가 50점이상 데이터 가산점 10%를 부여하시오
8. 국어점수 top5 구하시오
9. 국어점수 70점시상 합격 아니면 불합격
9. 국어점 70점 이상시 데이터 삭제

In [ ]:
kor = np.array([60,55,70,30,20,90])

In [ ]:
#1.
kor.max()
#2
kor[kor>=80]
#3
kor[(kor>=50) & (kor<=80)]
#4
kor.mean()
#5
kor.sum()
#6
np.delete(kor,kor<=40)
# 7
kor[kor>=50]*1.1
#8
np.sort(kor)[::-1][0:5]
#9
np.select([kor>=70,kor<70], ['합격','불합격']) # 40이상이면 a 20 이상 b 이런식으로 매칭 np.select()

array(['불합격', '불합격', '합격', '불합격', '불합격', '합격'], dtype='<U3')

In [ ]:
np.delete(kor,kor<=40)

array([60, 55, 70, 90])

In [ ]:
np.__version__

'1.25.2'

In [ ]:
kor*np.where(kor>=50,1.1,kor)

array([ 66. ,  60.5,  77. , 900. , 400. ,  99. ])