<a href="https://colab.research.google.com/github/dlvvkfl88/MSAISCHOOL/blob/main/MS_AI_SCHOOL_53%EC%9D%BC%EC%B0%A8_%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%A6%9D%EA%B0%95%EB%9D%BC%EB%B2%A8%EB%A7%814.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 복잡한 파이프라인 정의 augmentation s

## Cutout 이미지 증강 논문

-- Dataset and Data Loader

In [ ]:
# 이제 학습용으로 쓰기위해 분리 나누기 알아야함

# 정형 데이터셋 나누기 간단 실습

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
url = "https://raw.githubusercontent.com/mGalarnyk/Tutorial_Data/master/King_County/kingCountyHouseData.csv"
df = pd.read_csv(url)

print(df)

               id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00   
1      6414100192  20141209T000000  538000.0         3       2.25   
2      5631500400  20150225T000000  180000.0         2       1.00   
3      2487200875  20141209T000000  604000.0         4       3.00   
4      1954400510  20150218T000000  510000.0         3       2.00   
...           ...              ...       ...       ...        ...   
21608   263000018  20140521T000000  360000.0         3       2.50   
21609  6600060120  20150223T000000  400000.0         4       2.50   
21610  1523300141  20140623T000000  402101.0         2       0.75   
21611   291310100  20150116T000000  400000.0         3       2.50   
21612  1523300157  20141015T000000  325000.0         2       0.75   

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7   
1             2570      7242   

## 정형 데이터 학습 중간 평가 테스트

In [ ]:
columns = ['bedrooms', 'bathrooms','sqft_living','sqft_lot','floors','price']
df = df.loc[:,columns]

print(df)

       bedrooms  bathrooms  sqft_living  sqft_lot  floors     price
0             3       1.00         1180      5650     1.0  221900.0
1             3       2.25         2570      7242     2.0  538000.0
2             2       1.00          770     10000     1.0  180000.0
3             4       3.00         1960      5000     1.0  604000.0
4             3       2.00         1680      8080     1.0  510000.0
...         ...        ...          ...       ...     ...       ...
21608         3       2.50         1530      1131     3.0  360000.0
21609         4       2.50         2310      5813     2.0  400000.0
21610         2       0.75         1020      1350     2.0  402101.0
21611         3       2.50         1600      2388     2.0  400000.0
21612         2       0.75         1020      1076     2.0  325000.0

[21613 rows x 6 columns]


In [ ]:
features_data = ['bedrooms', 'bathrooms','sqft_living','sqft_lot','floors','price'] #  학습
target_data = ['price'] # 라벨 target 데이터

x_data = df.loc[:,features_data]
y_data = df.loc[:,target_data]

print(x_data)
print(y_data)

       bedrooms  bathrooms  sqft_living  sqft_lot  floors     price
0             3       1.00         1180      5650     1.0  221900.0
1             3       2.25         2570      7242     2.0  538000.0
2             2       1.00          770     10000     1.0  180000.0
3             4       3.00         1960      5000     1.0  604000.0
4             3       2.00         1680      8080     1.0  510000.0
...         ...        ...          ...       ...     ...       ...
21608         3       2.50         1530      1131     3.0  360000.0
21609         4       2.50         2310      5813     2.0  400000.0
21610         2       0.75         1020      1350     2.0  402101.0
21611         3       2.50         1600      2388     2.0  400000.0
21612         2       0.75         1020      1076     2.0  325000.0

[21613 rows x 6 columns]
          price
0      221900.0
1      538000.0
2      180000.0
3      604000.0
4      510000.0
...         ...
21608  360000.0
21609  400000.0
21610  402101.

# 데이터 나누기 train va ltest


In [ ]:
x_train , x_val_list , y_train, y_val_list = train_test_split(x_data ,y_data, random_state=777, test_size=0.8)
x_val , x_test, y_val ,y_test = train_test_split(x_val_list ,y_val_list, random_state=777, test_size=0.5)
print("변경되기전 데이터양 -----")
print("x_data 크기 : ",x_data.shape)
print("x_data 크기 : ",y_data.shape)
print("x_train 크기 : ",x_train.shape)
print("y_train 크기 : ",y_train.shape)
print("x_val 크기", x_val_list.shape)
print("y_val 크기", y_val_list.shape)

print("변경후")
print(x_val.shape)
print(y_val.shape)
print(x_test.shape)
print(y_test.shape)

변경되기전 데이터양 -----
x_data 크기 :  (21613, 6)
x_data 크기 :  (21613, 1)
x_train 크기 :  (4322, 6)
y_train 크기 :  (4322, 1)
x_val 크기 (17291, 6)
y_val 크기 (17291, 1)
변경후
(8645, 6)
(8645, 1)
(8646, 6)
(8646, 1)


## PySpark

## PyTorch
PyTorch와 Tensorflow 가 논쟁이 서로 많다
연구보단 tensor는 아직도 여전히 서비스분야 많이 쓰임
이 과정에선 tensor 안할예쩡

In [2]:
import torch
import torchvision
import numpy as np

print("Torch 버전 ", torch.__version__)
print("Torch 버전 ", torchvision.__version__)

Torch 버전  2.0.1+cu118
Torch 버전  0.15.2+cu118


# PyTorch - 텐서 기본실습

In [ ]:
# 텐서 초기화하기 데이터터로부터 직접 텐서를 생성가능합니다. 데이터의 자료형은 자동으로 유추합니다.
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

# Numpy 배열로 부터 생성
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np) # 이래도 텐서로 형성

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


In [ ]:
x_ones = torch.ones_like(x_data)
print(f"ones Tensor : \n{x_ones}")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data속성을 덮어씁니다
print(f"Random Tensor :\n{x_rand}")


# torch.rand_like() 주어진 입력 텐서와 동일한 크기의 텐서를 생성하고 모든
# 요소를 랜덤한 값을 채우고 타입지정시 그타입 변함
# 0과 1사이의 랜덤한 값으로 초기화 되고 데이터타입유형은 dtype=torch.float 지정됩니다.

ones Tensor : 
tensor([[1, 1],
        [1, 1]])
Random Tensor :
tensor([[0.9100, 0.5611],
        [0.7259, 0.3249]])


In [ ]:
# 무작위 or 상수 값을 사용하기
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

# 유효 범위를 최솟값~최대값 6~10
shape_temp = (5,6)
min_val = 6
max_val = 10
rand_tensor_temp = torch.rand(shape_temp) * (max_val - min_val) + min_val
print(rand_tensor_temp)

tensor([[0.5116, 0.7276, 0.7415],
        [0.5573, 0.2732, 0.5072]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[9.2771, 9.3521, 8.9819, 9.6294, 8.4272, 9.2047],
        [7.9939, 8.3846, 6.0838, 7.8653, 7.7730, 9.9669],
        [7.8193, 8.7660, 6.5997, 9.0515, 6.0489, 7.1890],
        [9.7977, 7.6129, 9.2056, 9.2035, 9.1207, 8.7681],
        [8.6300, 7.6520, 9.7236, 8.7955, 7.4388, 8.2108]])


## 표준 인덱싱 과 슬라이싱

In [9]:
tensor_1 = torch.ones(4,4)
tensor_1[:,3] = 0

tensor_2 = torch.ones(4,4)
tensor_2[:1] = 2

print(tensor_1) # 넘파이랑 슬라이싱 같음

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])


In [10]:
# 텐서 합치기

t1 = torch.cat([tensor_1, tensor_1, tensor_1], dim=1)
t1

tensor([[1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.]])

In [12]:
t_mult = tensor_1.mul(tensor_2)
print(t_mult)

print(tensor_1 * tensor_2) # 위와 아래 같음

tensor([[2., 2., 2., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])
tensor([[2., 2., 2., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])


In [15]:
# 행렬 곱
print(tensor_2 @ tensor_2.T)
print(tensor_2.matmul( tensor_2.T))

tensor([[16.,  8.,  8.,  8.],
        [ 8.,  4.,  4.,  4.],
        [ 8.,  4.,  4.,  4.],
        [ 8.,  4.,  4.,  4.]])
tensor([[16.,  8.,  8.,  8.],
        [ 8.,  4.,  4.,  4.],
        [ 8.,  4.,  4.,  4.],
        [ 8.,  4.,  4.,  4.]])


In [18]:
t = torch.ones(5)
print(t)
n = t.numpy()

print(n) # numpy와 메모리 공유하므로 텐서와 똑같은 값나옴 변경해도
t.add_(1) # t에 메모리와 n이 같음
print(t)
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Pytorch View 쓰기 이건  numpy reshape과 같음 텐서의 크기
원소의 수를 유지하면서 변경하기

In [24]:
"""
파이 토치 텐서의 뷰는 넘파이 Reshape 와같은역학
Reshape > 텐서의 크기를 변경해주는 역할
"""
t_temp = np.array([[[[0,1,2], [3,4,5,], [6,7,8],[9,10,11]]]])
ft = torch.FloatTensor(t_temp)
print(ft)
print(ft.shape)

# 이제 ft view를 2차원 텐서로 변경
# -1 : 나는 값을 모르니 파이토치 한테 알아서 해 두번쨰 차원은 3으로 가지도록
print(ft.view([-1,3])) # -1 한차원줄임
print(ft.view([-1,3]).shape)

tensor([[[[ 0.,  1.,  2.],
          [ 3.,  4.,  5.],
          [ 6.,  7.,  8.],
          [ 9., 10., 11.]]]])
torch.Size([1, 1, 4, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [25]:
#  스퀴즈 -> 1차원을 제거 차원이 1인경우에 해당 차원 제거

ft = torch.FloatTensor(([0],[1],[2]))

print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [26]:
print(ft.squeeze())
print(ft.squeeze().shape) # 1차원벡터가 되버림

tensor([0., 1., 2.])
torch.Size([3])


In [28]:
'''
언스퀴즈 - 특정위치 1인 차원 추가
'''
ft_temp  = torch.Tensor([0,1,2])
print(ft_temp.shape) # 1차원 벡터인 상황

# 첫번쨰차원에서 1차원 추가
# 인덱스 0
print(ft_temp.unsqueeze(0))
print(ft_temp.unsqueeze(0).shape) # 2차원이 되버림

torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [29]:
# 뷰를 통해서 똑같은거 가능
print(ft_temp.view(1,-1))
print(ft_temp.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])
