<a href="https://colab.research.google.com/github/dlvvkfl88/MSAISCHOOL/blob/main/MS_AI_SCHOOL_45%EC%9D%BC%EC%B0%A8_%EC%9D%B4%EB%AF%B8%EC%A7%80%EB%B6%84%EC%84%9D(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 싸이킷런 손글씨 데이터를 활용하여 특성 행렬을 표준화 처리 및 주성분 특성 줄이기

In [7]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn import datasets

In [8]:
digits = datasets.load_digits() # 8x8 크기 손글씨 숫자
feature = StandardScaler().fit_transform(digits.data) # 표준화 처리
print(feature)

[[ 0.         -0.33501649 -0.04308102 ... -1.14664746 -0.5056698
  -0.19600752]
 [ 0.         -0.33501649 -1.09493684 ...  0.54856067 -0.5056698
  -0.19600752]
 [ 0.         -0.33501649 -1.09493684 ...  1.56568555  1.6951369
  -0.19600752]
 ...
 [ 0.         -0.33501649 -0.88456568 ... -0.12952258 -0.5056698
  -0.19600752]
 [ 0.         -0.33501649 -0.67419451 ...  0.8876023  -0.5056698
  -0.19600752]
 [ 0.         -0.33501649  1.00877481 ...  0.8876023  -0.26113572
  -0.19600752]]


## 99%의 분산을 유지하도록PCA 클래스 객체 생성

In [9]:
pca = PCA(n_components=0.99, whiten=True)
features_pca = pca.fit_transform(feature) # PCA 수행

print("원본 특성갯수 >>", feature.shape[1])
print("원본 특성갯수 >>", features_pca.shape[1])


원본 특성갯수 >> 64
원본 특성갯수 >> 54


# 사이킷런 손글씨 데이터를 활용하여 주성분 줄이기 차이

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
# 데이터 정규화 후 분류 모델 확인
scaler = StandardScaler()
x_train_norm = scaler.fit_transform(x)

NameError: ignored

In [13]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# 데이터 불러오기

In [14]:
digits= load_digits()

# 진짜 차이가 있는지 체크하기 위해 -> 정규화 하지 않은 데이터로 분류 모델 훈련
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target,test_size=0.2, random_state=777)

print(len(x_train), len(x_test))
print(len(y_train), len(y_test))

1437 360
1437 360


# 모델 불러오기

In [15]:
model = LogisticRegression()

model.fit(x_train, y_train)
y_pred = model.predict(x_test)

no_standardScaler_acc_score = accuracy_score(y_test, y_pred) # 정답치 예측지 비교해서 맞으면 1 0 카운트 전부더해주고 / 전체데이터로 나눠줌

print(no_standardScaler_acc_score)

0.95


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# StandardScaler 적용후 -> ACC

In [16]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_norm = scaler.fit_transform(x_train)
x_test_norm = scaler.transform(x_test)
model_norm = LogisticRegression()
model_norm.fit(x_train_norm , y_train)
y_pred_norm = model_norm.predict(x_test_norm)


standardScale_acc_score = accuracy_score(y_test, y_pred_norm)
print(standardScale_acc_score)

0.95


실습 - 03

In [17]:
from sklearn.decomposition import KernelPCA
from sklearn.datasets import make_circles

In [18]:
# 선형적으로  구분되지 않은 데이터를 만들기

feature,_ = make_circles(n_samples=1000, random_state=777, noise=0.1, factor=0.1)

print(feature)

[[-0.02313275  0.15282194]
 [ 0.8626983   0.46556009]
 [ 0.05905661 -0.05048386]
 ...
 [-0.10071513 -0.1814104 ]
 [ 0.10461224  0.08710802]
 [ 0.28894733  0.97460534]]


# 방사 기저함수를 사용하여 커널 pca를 적용

In [19]:
kcpa = KernelPCA(kernel='rbf', gamma=15, n_components=1)
# kcpa rbf =

feature_rbf = kcpa.fit_transform(feature)
print("원본 특성 갯수:", feature.shape[1])
print("줄어든 특성 갯수:", feature_rbf.shape[1])



원본 특성 갯수: 2
줄어든 특성 갯수: 1


# 선형 판별 분석 LDA실습

In [20]:
from sklearn import datasets
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [21]:
iris = datasets.load_iris() # 붗꽃 데이터셋 로드
features = iris.data
target = iris.target


print(features, target)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [22]:
lda = LinearDiscriminantAnalysis(n_components=1)
features_lda = lda.fit(features, target).transform(features)

print("원본 특성 갯수 >>>", features.shape[1])
print("줄어든 특성 갯수 >>>", features_lda.shape[1])

원본 특성 갯수 >>> 4
줄어든 특성 갯수 >>> 1


# 범주형 데이터 분석

In [23]:
import numpy as np
from sklearn.preprocessing import LabelBinarizer,MultiLabelBinarizer

In [24]:
feature = np.array((['가나다라'],
                    ['가나다라'],
                    ['아바하자'],
                    ['카나다사']))

print(feature)
# 원핫인코더 생성
ont_hot = LabelBinarizer()
ont_hot.fit_transform(feature)

# 특성 클래스 확인
print(ont_hot.classes_)

[['가나다라']
 ['가나다라']
 ['아바하자']
 ['카나다사']]
['가나다라' '아바하자' '카나다사']


# 다중 클래스 특성에 대한 처리

In [25]:
multiclass_feature = [('가나다라마'), ('아자바하나'),
                      ('자다가나라'), ('자다나타하'),
                      ('라마바다나'), ('아자바하나'),
                      ('가나다라마'), ('아자바하나'),
                      ]

one_hot_mult = MultiLabelBinarizer()
one_hot_mult.fit_transform(multiclass_feature)
print(one_hot_mult.classes_)

['가' '나' '다' '라' '마' '바' '아' '자' '타' '하']


# 문자열과 타깃 데이터 원-핫 인코딩


In [26]:
from sklearn.preprocessing import OneHotEncoder

str_feature = ([['안녕',1],
                ['저녁',2],
                ['안녕',1],
                ['점심',3]])



one_hot_encoder = OneHotEncoder(sparse=False)

# One Hot Encoder -> 입력 특성 배열은 모두 범주형
one_hot_encoder.fit_transform(str_feature)
print(one_hot_encoder.categories_)

[array(['안녕', '저녁', '점심'], dtype=object), array([1, 2, 3], dtype=object)]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


## 순서가 있는 범주형 특성 인코딩

- 순서가 있는 클래스는 순서 개념을 가진 수치값을 ㅗ변환
딕셔너리 사용해서 -> 특성

In [27]:
import pandas as pd

In [28]:
# 특성 데이터 생성
dataframe = pd.DataFrame({
    'Score':["Low", "Low", "Medium","Medium","High"]
})
print(dataframe)

    Score
0     Low
1     Low
2  Medium
3  Medium
4    High


# 매핑 딕셔너리 생성

In [29]:
scale_mapper = {
    "Low":1,
    "Medium":2,
    "High":3
}

print(scale_mapper)

{'Low': 1, 'Medium': 2, 'High': 3}


In [30]:
data = dataframe["Score"].replace(scale_mapper)

print(data)

0    1
1    1
2    2
3    2
4    3
Name: Score, dtype: int64


# 1-2 순서가 있는 범주형 특성 인코딩

In [31]:

from sklearn.preprocessing import OrdinalEncoder

feature_array = np.array((['Low', 10],
                           ['High', 40],
                           ['Medium', 3],))

ordinal_encoder = OrdinalEncoder()
one_hot_encoder.fit_transform(feature_array)

print(ordinal_encoder.categories)

auto


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


# 1-3 순서가 있는 범주형 특성 인코딩 ## 특성 딕셔너리 인코딩

In [32]:
from sklearn.feature_extraction import DictVectorizer

In [33]:
# 딕셔너리 생성
data_dict = [{"Red":2, "Blue":4},
             {"Red":2, "blue":3},
             {"Red":1, "Yellow":2},
             {"Red":1, "Yellow":2}]




dictVectorizer = DictVectorizer(sparse=False)

feature_dict = dictVectorizer.fit_transform(data_dict)

print(feature_dict)

feature_dict_name = dictVectorizer.get_feature_names_out()
print(feature_dict_name)

dict_data = pd.DataFrame(feature_dict, columns=feature_dict_name)

print(dict_data)

[[4. 2. 0. 0.]
 [0. 2. 0. 3.]
 [0. 1. 2. 0.]
 [0. 1. 2. 0.]]
['Blue' 'Red' 'Yellow' 'blue']
   Blue  Red  Yellow  blue
0   4.0  2.0     0.0   0.0
1   0.0  2.0     0.0   3.0
2   0.0  1.0     2.0   0.0
3   0.0  1.0     2.0   0.0


# 범주형 데이터 - 누락된 클래스 값 대처하기 01

In [34]:
from sklearn.neighbors import KNeighborsClassifier

In [35]:
x = np.array([[0,2.10,1.48],
              [1.,1.18,1.33],
              [0,1.22,1.27],
              [1,-0.20,-1.15]])

x_with_nan = np.array([[np.nan, 0.87 , 1.33],
                       [np.nan, -0.67, -0.22]])

clf = KNeighborsClassifier(3, weights = 'distance')

print(x[:,1:])
print(x[:,0])


[[ 2.1   1.48]
 [ 1.18  1.33]
 [ 1.22  1.27]
 [-0.2  -1.15]]
[0. 1. 0. 1.]


In [36]:
train_model = clf.fit(x[:,1:], x[:,0])

imputer_values = train_model.predict(x_with_nan[:,1:]) # 누락된 값의 클래스 예측

x_with_imputer = np.hstack((imputer_values.reshape(-1,1), x_with_nan[:,1:]))
data = np.vstack((x_with_imputer, x )) # 두 특성 핼렬을 연결
print(data)

[[ 0.    0.87  1.33]
 [ 1.   -0.67 -0.22]
 [ 0.    2.1   1.48]
 [ 1.    1.18  1.33]
 [ 0.    1.22  1.27]
 [ 1.   -0.2  -1.15]]


# 누락된 클래스 값 대처하기 -02
-누락된 값을 특성에서 가장 자주 등장하는 값으로 채우기

In [37]:
from sklearn.impute import SimpleImputer
import numpy as np

In [38]:
x_complete = np.vstack((x_with_nan, x ))
impute = SimpleImputer(strategy='most_frequent')
data_impute = impute.fit_transform(x_complete)

print(data_impute)

[[ 0.    0.87  1.33]
 [ 0.   -0.67 -0.22]
 [ 0.    2.1   1.48]
 [ 1.    1.18  1.33]
 [ 0.    1.22  1.27]
 [ 1.   -0.2  -1.15]]


## 텍스트 데이터 처리

In [39]:
import re

In [40]:
# 텍스트 정제
text_data = [" import re 모듈은 파이썬에서 정규 표현식을 사용하기 위해 제공되는 내장 모듈입니다. ???" ,
             "  정규 표현식은 문자열 패턴을 검색, 추출, 대체 또는 분할하는 데 사용됩니다. !!!!!"]

In [41]:
# 공백 문자 제거
strip_whitespace = [string.strip() for string in text_data] #공백문자제거

strip_whitespace

['import re 모듈은 파이썬에서 정규 표현식을 사용하기 위해 제공되는 내장 모듈입니다. ???',
 '정규 표현식은 문자열 패턴을 검색, 추출, 대체 또는 분할하는 데 사용됩니다. !!!!!']

# " import 공백ㅇ이 string.strip()을 통해 "import 됨

In [42]:
# 마침표 제거
remove_periods = [string.replace(".","") for string in strip_whitespace ]

remove_periods

['import re 모듈은 파이썬에서 정규 표현식을 사용하기 위해 제공되는 내장 모듈입니다 ???',
 '정규 표현식은 문자열 패턴을 검색, 추출, 대체 또는 분할하는 데 사용됩니다 !!!!!']

In [47]:
# 구두점 !! 삭제
import sys
import unicodedata

temp = dict.fromkeys(i for i in range(sys.maxunicode) if unicodedata.category(chr(i)).startswith('P'))

data = [string.translate(temp) for string in text_data]
print(data)

[' import re 모듈은 파이썬에서 정규 표현식을 사용하기 위해 제공되는 내장 모듈입니다 ', '  정규 표현식은 문자열 패턴을 검색 추출 대체 또는 분할하는 데 사용됩니다 ']


### 텍스트 토큰화
-텍스트를 개별단어로 나누기

In [50]:
from nltk.tokenize import sent_tokenize # 문장기준
from nltk.tokenize import word_tokenize # 단어기준
import nltk

# 구두점 데이터 다운로드
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [52]:
string = "모듈은 정규 표현식을 사용하여 문자열에서 패턴을 찾고 조작하는 데 사용되는 파이썬 내장 모듈입니다."
word_data = word_tokenize(string) # 단어를 토큰 기준으로 나눕니다.
print(word_data)

['모듈은', '정규', '표현식을', '사용하여', '문자열에서', '패턴을', '찾고', '조작하는', '데', '사용되는', '파이썬', '내장', '모듈입니다', '.']


In [53]:
sent_string = "모듈은 정규 표현식을 사용하여 문자열에서 패턴을 찾고 조작하는 데 사용되는 파이썬 내장 모듈입니다. 정규 표현식을 사용하여 문자열에서 패턴을 찾고 조작하는 데 사용되는 파이썬 내장 모듈입니다."

In [54]:
sent_data = sent_tokenize(sent_string)

print(sent_data)

['모듈은 정규 표현식을 사용하여 문자열에서 패턴을 찾고 조작하는 데 사용되는 파이썬 내장 모듈입니다.', '정규 표현식을 사용하여 문자열에서 패턴을 찾고 조작하는 데 사용되는 파이썬 내장 모듈입니다.']


# 불용어 삭제

In [55]:
from nltk.corpus import stopwords
nltk.download('stopwords') # 불용어 사전리스트

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [58]:
tokenized_words = ["i","am","going","to","the","storm", "and","park"]

stop_words = stopwords.words('english')

# 불용어 삭제
filterd_words = [word for word in tokenized_words if word not in stop_words ]

# 불용어 홗인

stop_data = stop_words

print(filterd_words)

['going', 'storm', 'park']


## 어간 추출 : 단어으 ㅣ어간을 구부나형 기본의미를 유지하면서 어미를 제거합니다.

In [59]:
from nltk.stem.porter import PorterStemmer



In [60]:
# 단어 토큰 생성
tokenized_words_temp = ['i','am','humbled','by','traditional','meeting']

# 어간 추출기 생성
porter = PorterStemmer()

word_list_temp = []
# 어간 추출기를 적용
for word in tokenized_words_temp :
  word_list_temp.append(porter.stem(word))


print(word_list_temp)

['i', 'am', 'humbl', 'by', 'tradit', 'meet']


## 품사 태깅

In [62]:
from nltk import pos_tag
from nltk import word_tokenize



In [63]:
nltk.download("averaged_perceptron_tagger")

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [64]:
text_data_tag= "Chris loved outdoor running"

text_tagger = pos_tag(word_tokenize(text_data_tag))
print(text_tagger)

[('Chris', 'NNP'), ('loved', 'VBD'), ('outdoor', 'RP'), ('running', 'VBG')]
