<a href="https://colab.research.google.com/github/dlvvkfl88/MSAISCHOOL/blob/main/Pandas_OREILLY_181page.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from pandas import Series , DataFrame

## 시리즈 1차원 배열 자료구조

In [ ]:
obj = pd.Series([4,7,-5,3])

obj

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
obj.values

array([ 4,  7, -5,  3])

In [ ]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
obj2 = pd.Series([4,7,-5,3], index = ['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [ ]:
obj2['a']

-5

In [ ]:
obj2['d'] = 6

In [ ]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [ ]:
obj2[obj2 > 0 ]

d    6
b    7
c    3
dtype: int64

In [ ]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [ ]:
import numpy as np

In [ ]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [ ]:
'b' in obj2

True

In [ ]:
sdata = {'Ohio': 35000, 'Texas':71000, 'Oregon': 16000, 'Utah': 5000}

obj3 = pd.Series(sdata)

obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

obj4 = pd.Series(sdata, index= states)

obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [ ]:
pd.isnull(obj4)

pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [ ]:
obj4.name = 'population'

obj4.index.name = 'state'

obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

### 5.1.2 DataFrame 2차원배열

In [ ]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
        'year': [2000,2001,2002,2001,2002,2003],
        'pop': [1.5,1.7,3.6,2.4,2.9,3.2]}

frame = pd.DataFrame(data)

In [ ]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [ ]:
pd.DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [ ]:
frame2 = pd.DataFrame(data,columns=['year','state','pop','debt'],
                      index = ['one','two','three','four',
                               'five','six'])

frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [ ]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [ ]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [ ]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [ ]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [ ]:
val = pd.Series([-1.2,-1.5,-1.7] , index= ['two','four','five'])

frame2['debt'] = val

In [ ]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [ ]:
frame2['eastern'] = frame2.state == 'Ohio'

frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [ ]:
del frame2['eastern']

frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [ ]:
pop = {'Nevada': {2001:2.4,2002:2.9},
       'Ohio': {2000:1.5,2001:1.7 , 2002:3.6}}

In [ ]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [ ]:
frame3 = pd.DataFrame(pop)

frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [ ]:
frame3.T # 전치가능하다

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [ ]:
pd.DataFrame(pop , index = [2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [ ]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [ ]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## 5.1.3 색인 객체

In [ ]:
obj = pd.Series(range(3), index= ['a','b','c'])
index = obj.index


index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
index[1:]

Index(['b', 'c'], dtype='object')

In [ ]:
labels = pd.Index(np.arange(3))

labels

Int64Index([0, 1, 2], dtype='int64')

In [ ]:
obj2 = pd.Series([1.5,-2.5,0], index= labels)

obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [ ]:
obj2 = obj.reindex(['a','b','c','d','e'])

obj2

a    0.0
b    1.0
c    2.0
d    NaN
e    NaN
dtype: float64

In [ ]:
obj3 = pd.Series(['blue','purple','yellow'], index = [0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [ ]:
frame = pd.DataFrame(np.arange(9).reshape(-1,3),
                     index = ['a','b','c'],
                     columns = ['Ohio','Texas','California'])

frame

Ohio  Texas  California
a     0      1           2
b     3      4           5
c     6      7           8

In [ ]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   3.0    4.0         5.0
c   6.0    7.0         8.0
d   NaN    NaN         NaN

## 로우 컬럼값의 삭제

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index = ['Ohio', 'Colorado','Utah', 'New York'],
                    columns = ['one','two','three','four'])

data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [ ]:
data.drop(['two','four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

## 5.2.4 정수색인

In [4]:
import pandas as pd
import numpy as np

In [7]:
ser = pd.Series(np.arange(3.))
ser


0    0.0
1    1.0
2    2.0
dtype: float64

In [12]:
ser2 = pd.Series(np.arange(3.), index= ['a','b','c']) # 정수가아닌 문자 인덱스 사용시 -1 -2 인덱스접근가능

ser2[-2]

1.0

In [13]:
ser[:1]

0    0.0
dtype: float64

### 5.2.5 산술 연산과 데이터 정렬

In [14]:
s1 = pd.Series([7.3,-2.5,3.4,1.5], index = ['a','c','d','e'])

s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],
               index = ['a','c','e','f','g'])

In [15]:
s1,s2

(a    7.3
 c   -2.5
 d    3.4
 e    1.5
 dtype: float64,
 a   -2.1
 c    3.6
 e   -1.5
 f    4.0
 g    3.1
 dtype: float64)

In [16]:
s1+s2 # 같은 인덱스끼리 더해짐 없으면 Nana 뜸

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [21]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns = list('bcd'), index = ['Ohio','Texas', 'Colorado'])

df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [22]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)), columns = list('bde'),
                   index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [23]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [25]:
df1 = pd.DataFrame({'A':[1,2]})

df2 = pd.DataFrame({'B':[3,4]})

df1

df2

B
0  3
1  4

In [26]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

## DataFrmae과 Series 간의 연산

In [28]:
arr = np.arange(12.).reshape((3,4))

arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [29]:
arr[0]

array([0., 1., 2., 3.])

In [30]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                     columns = list('bde'),
                     index= ['Utah','Ohio','Texas', 'Oregon'])

series = frame.iloc[0]

## 5.2.6 함수 적용과 매핑

In [31]:
frame = pd.DataFrame(np.random.randn(4,3), columns = list('bde'),
                     index = ['Utah', ' Ohio','Texas','Oregon'])

frame

b         d         e
Utah   -2.587731 -0.187326 -1.182551
 Ohio   0.616399  1.128749 -1.409329
Texas  -1.347874 -1.298605  0.341565
Oregon  0.920382 -0.148433 -0.948951

In [33]:
f = lambda x : x.max() - x.min()

frame.apply(f)

frame.apply(f, axis='columns')

Utah      2.400405
 Ohio     2.538078
Texas     1.689438
Oregon    1.869333
dtype: float64

In [35]:
def f(x):
    return pd.Series([x.min(), x.max()], index = ['min','max'])

In [36]:
frame.apply(f)

b         d         e
min -2.587731 -1.298605 -1.409329
max  0.920382  1.128749  0.341565

In [37]:
format = lambda x : '%.2f' % x

frame.applymap(format)

b      d      e
Utah    -2.59  -0.19  -1.18
 Ohio    0.62   1.13  -1.41
Texas   -1.35  -1.30   0.34
Oregon   0.92  -0.15  -0.95

In [38]:
frame['e'].map(format)

Utah      -1.18
 Ohio     -1.41
Texas      0.34
Oregon    -0.95
Name: e, dtype: object

## 5.2.7 정렬과 순위

In [39]:
obj = pd.Series(range(4), index = ['d','a','b','c'])

obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [40]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                     index = ['three', 'one'],
                     columns = ['d','a','b','c'])

frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [42]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [43]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

## 객체값 정렬할떄

In [45]:
obj = pd.Series([4,7,-3,2])

obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [46]:
obj = pd.Series([4,np.nan,7,np.nan,-3,2])

obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [47]:
frame = pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [48]:
frame.sort_values(by='b') # 하나컬럼만 오름차순하려면

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [49]:
frame.sort_values(by=['a','b']) # 멀티컬럼 오름차순

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [51]:
obj = pd.Series([7,-5,7,4,2,0,4])

obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [52]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [53]:
obj.rank(ascending=False, method= 'max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [54]:
frame = pd.DataFrame({'b':[4.3,7,-3,2], 'a':[0,1,0,1],
                      'c':[-2,5,8,-2.5]})

frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [55]:
obj = pd.Series(range(5), index=  ['a','a','b','b','c'])

obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [57]:
obj.index.is_unique

False

In [58]:
obj['a']

a    0
a    1
dtype: int64

In [59]:
obj['c']

4

In [60]:
df = pd.DataFrame(np.random.randn(4,3), index=['a','a','b','b'])

df

0         1         2
a  0.752188  0.361269  0.841773
a -0.250755 -0.268371  0.243065
b  0.754617  1.335484  0.772188
b -0.849465  1.026011 -1.089000

In [61]:
df.loc['b']

0         1         2
b  0.754617  1.335484  0.772188
b -0.849465  1.026011 -1.089000

In [62]:
df = pd.DataFrame(np.random.randn(4,3), index = ['a','a','b','b'])

df

0         1         2
a -0.388746  0.413491 -0.113381
a  0.972115  0.524004 -1.142180
b  0.179895  0.143210  1.562460
b -0.782138 -0.256228  1.004278

In [63]:
df.loc['b']

0         1         2
b  0.179895  0.143210  1.562460
b -0.782138 -0.256228  1.004278

## 5.3 기술 통계 계산과 요약

In [64]:
df = pd.DataFrame([[1.4,np.nan], [7.1,-4.5],
                   [np.nan,np.nan], [0.75, -1.3]],
                  index = ['a','b','c','d'],
                  columns = ['one','two'])

df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [65]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [67]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [68]:
df.mean(axis='columns' , skipna = False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [70]:
df.idxmax() # 최댓값 색인과 간접통계 반환

one    b
two    d
dtype: object

In [71]:
df.cumsum() # 누적합 세로로

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [72]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000